### ISSUE TITLE
System.IO.IOException: Read-only file system : '/.dotnet'

### ISSUE THREAD

**Issue by nkosi23** [Thefrank/dotnet-freebsd-crossbuild#5]
When trying to launch an ASP.NET Core application in a jail having the root partition mounted on a read-only file system (but whose /usr/local and /tmp partitions are writable) I receive the following exception on application startup:

```
System.IO.IOException: Read-only file system : '/.dotnet'
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.CreateIfNotExists(IFileSystem fileSystem, String filePath)
   at Microsoft.DotNet.Configurer.FileSentinel.Create()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.AddPackageExecutablePath()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

Is there a way to modify the default path chosen by dotnet? I am using your latest release (7.0.203)

**Comment by Thefrank** [comment]
Never tried running dotNET in a read-only jail but you can try and set `DOTNET_RUNNING_IN_CONTAINER=true` environment variable and `DOTNET_ROOT=/path/to/dotnet`

There are a few more here but I don't think they apply: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables
